Repository mash-up-kr/Boilerplate_MongoDB_GraphQL_Redis, pull requests merged in 2021-02, with the labels that each got.

#8 댓글 MongoDB 모델, GraphQL 타입, 쿼리, 리졸버를 구현했습니다.
  .env.default
  README.md
  package.json
  src/domains/comments/index.js
  src/domains/comments/models/@types/comments.typedef.js
  src/domains/comments/models/@types/index.js
  src/domains/comments/models/comment.js
  src/domains/comments/models/index.js
  src/domains/comments/resolvers/addComment.js
  src/domains/comments/resolvers/addReply.js
  src/domains/comments/resolvers/comment.js
  src/domains/comments/resolvers/comments.js
  src/domains/comments/resolvers/editComment.js
  src/domains/comments/resolvers/index.js
  src/domains/comments/resolvers/removeComment.js
  src/domains/comments/resolvers/replies.js
  src/domains/comments/services/comment.service.js
  src/domains/index.js
  src/graphql.js
  src/mongodb.js
Labels: ‼ 우선순위 : 상, ☘️ 기능, 😭 어려움, 🤔 이야깃거리

#9 Hashtag MongoDB 모델, GraphQL 타입, 쿼리, 리졸버 구현
  src/domains/hashtags/index.js
  src/domains/hashtags/models/@types/hashtags.typedef.js
  src/domains/hashtags/models/@types/index.js
  src/domains/hashtags/models/hashtag.js
  src/domains/hashtags/models/index.js
  src/domains/hashtags/resolvers/addHashtag.js
  src/domains/hashtags/resolvers/createHashtag.js
  src/domains/hashtags/resolvers/hashtag.js
  src/domains/hashtags/resolvers/hashtags.js
  src/domains/hashtags/resolvers/index.js
  src/domains/index.js
  src/graphql.js
Labels: ‼ 우선순위 : 상, ☘️ 기능, 😭 어려움

#10 Feature/posts 작업내용
  package-lock.json
  package.json
  src/domains/posts/models/@types/posts.typedef.js
  src/domains/posts/models/index.js
  src/domains/posts/models/post.js
  src/domains/posts/resolvers/addPosts.js
  src/domains/posts/resolvers/editPost.js
  src/domains/posts/resolvers/post.js
  src/domains/posts/resolvers/posts.js
  src/domains/posts/resolvers/removePost.js
  src/mongodb.js
Labels: ‼ 우선순위 : 상, ☘️ 기능

#11 댓글, 포스트, 해쉬태그를 리팩터링 하였습니다.
  package.json
  src/domains/comments/services/comment.service.js
  src/domains/comments/services/index.js
  src/domains/hashtags/models/@types/hashtags.typedef.js
  src/domains/hashtags/models/hashtag.js
  src/domains/hashtags/resolvers/addHashtag.js
  src/domains/hashtags/resolvers/createHashtag.js
  src/domains/hashtags/resolvers/hashtag.js
  src/domains/hashtags/resolvers/hashtags.js
  src/domains/hashtags/resolvers/index.js
  src/domains/hashtags/services/hashtag.service.js
  src/domains/hashtags/services/index.js
  src/domains/posts/models/@types/posts.typedef.js
  src/domains/posts/models/post.js
  src/domains/posts/resolvers/addPost.js
  src/domains/posts/resolvers/addPosts.js
  src/domains/posts/resolvers/editPost.js
  src/domains/posts/resolvers/index.js
  src/domains/posts/resolvers/post.js
  src/domains/posts/resolvers/posts.js
  src/domains/posts/resolvers/removePost.js
  src/domains/posts/services/index.js
  src/domains/posts/services/post.service.js
  src/mongodb.js
Labels: 🔧 리팩터링

#12 chore: 메서드 분리 리팩터링
  src/domains/hashtags/services/hashtag.service.js
  src/domains/posts/services/post.service.js
  src/utils/deep_clone.js
Labels: 🔧 리팩터링

#13 최종 점검 배포
  .dockerignore
  .env.default
  .gitignore
  Dockerfile
  Dockerfile.nginx
  README.md
  configs/nginx.conf
  docker-compose.yml
  package-lock.json
  package.json
  src/app.js
  src/domains/comments/controllers/index.js
  src/domains/comments/index.js
  src/domains/comments/models/@types/comments.typedef.js
  src/domains/comments/models/@types/index.js
  src/domains/comments/models/comment.js
  src/domains/comments/models/index.js
  src/domains/comments/resolvers/addComment.js
  src/domains/comments/resolvers/addReply.js
  src/domains/comments/resolvers/comment.js
  src/domains/comments/resolvers/comments.js
  src/domains/comments/resolvers/editComment.js
  src/domains/comments/resolvers/index.js
  src/domains/comments/resolvers/removeComment.js
  src/domains/comments/resolvers/replies.js
  src/domains/comments/services/comment.service.js
  src/domains/comments/services/index.js
  src/domains/hashtags/index.js
  src/domains/hashtags/models/@types/hashtags.typedef.js
  src/domains/hashtags/models/@types/index.js
  src/domains/hashtags/models/hashtag.js
  src/domains/hashtags/models/index.js
  src/domains/hashtags/resolvers/addHashtag.js
  src/domains/hashtags/resolvers/hashtag.js
  src/domains/hashtags/resolvers/hashtags.js
  src/domains/hashtags/resolvers/index.js
  src/domains/hashtags/services/hashtag.service.js
  src/domains/hashtags/services/index.js
  src/domains/index.js
  src/domains/posts/index.js
  src/domains/posts/models/@types/index.js
  src/domains/posts/models/@types/posts.typedef.js
  src/domains/posts/models/index.js
  src/domains/posts/models/post.js
  src/domains/posts/resolvers/addPost.js
  src/domains/posts/resolvers/editPost.js
  src/domains/posts/resolvers/index.js
  src/domains/posts/resolvers/post.js
  src/domains/posts/resolvers/posts.js
  src/domains/posts/resolvers/removePost.js
  src/domains/posts/services/index.js
  src/domains/posts/services/post.service.js
  src/dotenv.js
  src/graphql.js
  src/index.js
  src/mongodb.js
  src/redis.js
  src/utils/deep_clone.js
  test/express.test.js
Labels: ‼ 우선순위 : 상, ☘️ 기능
